version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5555:5555"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
